apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCYPcgr1ug/89OMOsyyYzFKrQbgELj2hTK6LgiES0eRCMOuqqNV7rcRm0mZhvRwe20Dg/YgDHXFUjnAnZu3gjHqCEW6KMa+eKI5/gPKbbiiRvkKsURJkEhvRvG1bco2rawWEPx0Mwa5SulnS5nib3JGzB5ZLzFM4afgXJMuxGOTf7XtIFX/WtoEBfJNohmeDLwzFgwYK4/68+TW/TXtnw51OPA2wV9xX+6otRdtz4eu7Allizs98Zwp8ypzc+dNXQfhbCQg33hHB5ZHjqcTqENyyCukNPR89GcBMGxQSnWJEvv3mq1dGgCN9ylxTxENe3kDrnCPULsoKQbOY8Ju6rEJgQOcqK8hwjJwn7zKeKYYRQE1YEA34bw+ym1y4bIJA7Ba/FCZ/RgqiVYnTK4GLY8tcjK1t0On7kvlEh36zSczWDdmbyadRHxjDTaiGEqQT7opvEJrlexZagZMoobpdEsM4BPrwTcjit/Uk7I3SGImlsBlfqTJLBr5POyUOWiAdvdWaueNWTH4fLUzaNGiw8BUIHfc7WeAU9kE30to3tLbgTaW7sRt9PjliL/buTQCmdkj8HBfolKm85rJftdSVGUJqEcA1cBWptLZeVmLxmhEVC+Cwtbv6CEvapH6E+yhyRp+XvYy4tpd63o3nmI65zuYxfqD+gTx8sXR0SUPm2Jwa+Ys76z7SCkf6PWHLKADdMonOBrKHqs=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
