apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBp1Zo4Q2nHcppTnnk+AudDwnWg9x/JPPla7jzigg+tRVo2Jjyz/YBYSwU2/VQh9iKUmeqJaavNf8Aikd73lD03im+ClB2cO3xh9JnynS1utezHMvsw3wYR0+2edigkKiWxIuRbpu+kEcDKTB8IebPPt3jwO/kFxHLcsZEJ1eedjwXl0aOjUbaYrbcPx2mVNNomSqnqIynyh9DiAevnQdLV9zeqKXbbvevzAVuu68w0nPn1WT6FiIFGxf+Cfsx3dNeVLsI9AwYSAxmoOyFOWCW7k+Oug1WZvxAIr16/mHUlum4YHTJxIdotR8TzQbW4r8QKTGs7DqGvw4z2pWzeI32GwokSX+h4KSS0CCO2RVu2NtMgU/APLkz3u/0n5N8dJ4FebDJIGywh20DqmbwCZwiKzn9k+WKOJQqeP8Tbjyq8sLz4FxfdLntQ65L9cgEaELQTEzwGooYvNzwDQSHsZucXmXREmJqavN0MLH8rUaqmPuSM14hda+Hi4uABnGnhCuwHD5BfYr+AUki0TgafxF1gMj1nwDApNMvXuA386Z8GJ19vjgq1SotLuzKLuGiFcBr4DiDJwW8/KDNyuTV207sABuJuUrwLyQvjS1RqxxEivry9MLq9ZMkJx2Mzu7X83ltKSZg1xnjFV2bvy0lonSNSARzu3/2zQ32f1WTZkBfgu7T3KsQIFE9Xu6WxqcRNsUgffcGWEFI=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
