apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAgzgC70ImjsNyM12SjC7X5kCjTDjfwSy/M8d3gDmPP4WxAjsyU0USQP+a3+HuKCXpAv5xAB1Lq+rYjgKCKWdp8CCagTGp0h+/7qa2gOwOKp42DcIHwhiOUyf2/VsaWiluP5cDcxl9Mf8RPKpN8iQNShYi3TnWkibSAZMPEEo/M734bWQnGSqPhmbNK4jGntKXpCIg3CcpVfwbuOBPbeapUAyPZEk7W8r2Pj6WcxBfF1qNp0EmMRSmkkOBSnq3KqgG4/6NtqfoGgLpOa8lOY245UlfxB4VSoT+tDkM8FDSmYShqjLdiqM1HOyD+r79qztlgTNbQwdOa7NqdDGXqHiicddCOVCO+sPLm/YyoXd9/MzjBAG40Zpfb266Kam6a03+nFWWmYt+f9TcvZWiWJqurHnTpdsoVUUSjef0OkOSy+1YEAA67QPac9b6T/v4WaxdcjFDAPvkvIcpbePdbDuWwNaCMRLKsjaIghc1tJiKeUgQSa+zfR5KzanYJtMo6ygc++y9wmL8UdU7Zg/7TYf5eg8B7/19iQObyAhWDBZuFlFxzYGJUoEF8P7IVV1o++OQN4Gxx3kreZTAdBGBYPG9Q5VcEp41KaPPoEc1eu//f8O9bYoxkwaZt9UV5RGzjG83+CajafvqKhilQc5UMhoGQzLHY71qh1+NoUDyOwgXvTNWOdxjijsHYvK36vH6LULpIHSdpIns=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
