apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB8mlYy2zdRWM1yKHwlL8yzDLEOgxePvyLrepttQO2nR625wL/UBwBbGgDrTfufCmmUtVaxDqWtCcn12ebC8n9hvvGVraes8JdLvbOe/nbm1kDIrd9B5dseVTKYwLuNrdqdalG8lfNML51H2sRxWpVIU5CgEDLZjZqaFOlm3fJoW2L1N9q7ZgRjnbTHhK21DMg1r9M7ozL14AtJ244LkLscmne/o8GM2oocipSVr8o9aIP6/MPbZLbuTEIJzYCMo29qs5/aHSmQJt7qDbi3/cSbTEU/x1/queviibMXgNDPvNZk0CzzHZ177fPNd5oH2Cul2unFl6rhLk1yuu6nmHpVpmvgep9m3fqGWZVKQH/J15wft8kBbo9lcMiUbo15u4noQLXxfMpZIg6fYIuUqIoRAZQjY3RT/EPVHshFLiCVCbD17UbHFsrOD/6AI1wlsHexeswk87/ZmRimaB6qYHhThsCBpera7JKuPZ5xvsgoQSQSQJOQ3hJmYYZNIUjbw7Qy9vWlhOCmK5k7bf1NVNuL2eAiL3WsTg2CJbtpNFCWEAQ5SQQ8IviDNB1sPdhGD1kWlCEjNy6V5+JkxxvWbQEARrrknmdA26O1aYaOqLSjM8/x91vKLwj5ipxTlePky72sVv6LWJ5WCATK9cs6+CjvPYkXixETGm/N+PvWxpV6wVkh3FrNW9x4a948Z+w4Zy4kAjC+m/k=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
