apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  creationTimestamp: null
  name: deploy-from-source-task
  namespace: cicd
spec:
  inputs:
    params:
    - default: environments/cicd/base
      description: Path to the pipelines to apply
      name: PATHTODEPLOYMENT
      type: string
    - description: Namespace to deploy into
      name: NAMESPACE
      type: string
    - default: "false"
      description: If true run a server-side dryrun.
      name: DRYRUN
      type: string
    resources:
    - name: source
      type: git
  steps:
    command:
    - ./dry-run.sh
    image: quay.io/redhat-developer/k8s-kubectl
    name: run-kubectl
    resources: {}
    workingDir: /workspace/source
