apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  creationTimestamp: null
  name: deploy-from-source-task
  namespace: cicd
spec:
  inputs:
    params:
    - default: environments
      description: Path to the pipelines to apply
      name: PATHTODEPLOYMENT
      type: string
    - description: Namespace to deploy into
      name: NAMESPACE
      type: string
    - default: "false"
      description: If true run a server-side dryrun.
      name: DRYRUN
      type: string
    resources:
    - name: source
      type: git
  steps:
  - image: my-image  # contains /bin/my-binary
    script: |
      #!/usr/bin/env bash
      ./dry_run.sh
    resources: {}
    workingDir: /workspace/source
