apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCHi3fbvxYhbmd9a5zz+LTuTEQ6p1efV1ZnMGwk+ziBrlVm3Vw2Pk8fhhZG8h5MTJq61I08VfU6v1lov+ltOo6ZVDQGFaL90P5bYikCwf4wFlc7OPPmoQ+ZfvDEAKHyqurP/YxCwN9R62WGwlxsIJZXbN16d+V4ujRh1FwOOuZ5cya71lv4/74sTZQMsozSa371mXXwtOxv4Q4SBK0DupIiY0RIMlyh8UY2zuKlwaebCNOvSlgH0Fh50xr+pu11C/scp/nN12tlULGfYNTEi77hCJqMEEZpLUtm1vyVF+p0r7haCjq9p7y1ElFwHEkLajkXdRgZgFsp9KuDq/v8sVr7ndqni1xEBR3b7KI33vHUY19lqMRUhnO7UgobGoekxxGfu7A+ESadqm/sPAx7LbPjAC/TEFRynILKP7GMikZqLdv33UIkvXCg4ptkN8MdpXMDFmDqpwo11cRBM/9d087zBiMjsusI66FKC2heXxJtSRV1Um+JcuPU90/IUfv8RobVYnEVKYs0ai1z+qC7Vp3h59WNpxF10MAMQdT5ql2EfsOIMJCPHsl0D8ghtpaPrtTj8eKsmtKeMxDz3Ck6++Z87JygvkkNCQ1UrseaG91nPsdL8plZL3tSGjWFmBx3X3XzZKFza4e1Q7t11rPI/x2UP2SVfGbNOdMHX8hAX3nxz9DBc++aMPWfuLvbBB0bf85iwnw1ja4=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
