apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCm1Uy9ZhwGoEZyGTXHN/hfyOrmClYG1lYF4v7UETjjzR29IdTZSrXeKBsi/WPeve+BzoG9ZhlzgsdbVe62QeUrXucKHJjNSs0FNxbFrOW5VvMTP8t3/wf7grP+OlXvJnfeyVxUM7Z8+Od9Ul8VP956q1UXk9KmYSD4cRAykqbR2HUl5Wz+C/kSH5yHGKdAmcZZu3shQiV49XnTg0dM1TxcZtmaUyGY+x/PCWHZj21tpu8YnU2x9Jip+8e2xAUsSgQ0KAZy4VQtfRe1fstGVKDjHg0pV9D7sfqjgzWpHRfN6CY0LW3/5m3wUz0P9Y3gl1vbnfOK8iNjkjlUeCLFhLcKruB0etjkjcSDmNG2IULOv8jPxz/C/mfMH19AyZP93CPgZ/Yc5CT4HN0yzWSyPt1XTPJ1d7uQF8Jh1seEAzet91I/DDQnyf/lg4cbECNH5XuN6+PYd+RUXVeBYBEMlsupzeuwz/Rqp41Zlvk0tU48/3X+eoM9UY34Fzwg8aXyiT7RFb98bwZWi5Gw2X0oVRq4GRBNH8Lq8q09PDBmETC5qydx2eTeHrKBVB40BHG21B8sif/NZoAuPOF9IeAXnVYfwMC/ZqyvjIUTtcQWK1n2V298r9AhCafV3uW4XJhLBKYiNv91J/4DzATMWH1WUUcg7lUYKsfmVfmS9YlUerYaW4QwXlGz8/sQ7Y0Nh8R1V9bz231pyIg=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
